# Generated by Django 5.0.1 on 2024-02-04 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblisting_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
