# Generated by Django 5.0.1 on 2024-02-08 13:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='resume'),
        ),
    ]
